### ISSUE TITLE
RPC-CORE: dryRun(extrinsic: Bytes, at?: BlockHash): ApplyExtrinsicResult:: -32601: Method not found (node:35027) UnhandledPromiseRejectionWarning: Error: -32601: Method not found

### ISSUE THREAD

**Issue by Luca-Poggi** [kianenigma/kanaria-hatchery#2]
```
root@VMLuca:~/kanaria-hatchery/kanaria-hatchery# yarn run start --dust 100 --emotes 🌈 🚀 --endpoint ws://localhost:9944 --final-account Dr4EWpnWT7fPiW3QqrJQsmqmx5ssYiRCU49NyZxjdGEjka5 --id 6802595-24d573f4dfa1d7fd33-KAN-KANL-0000000000003414 --seed /root/kanaria-hatchery/address1.txt
yarn run v1.22.5
$ ./node_modules/.bin/ts-node ./src/index.ts --dust 100 --emotes 🌈 🚀 --endpoint ws://localhost:9944 --final-account Dr4EWpnWT7fPiW3QqrJQsmqmx5ssYiRCU49NyZxjdGEjka5 --id 6802595-24d573f4dfa1d7fd33-KAN-KANL-0000000000003414 --seed /root/kanaria-hatchery/address1.txt
2021-05-22 15:18:34        API/INIT: RPC methods not decorated: state_getChildReadProof
Connected to node: Kusama [ss58: 2]
emotes [ '🌈', '🚀' ]
account Dr4EWpnWT7fPiW3QqrJQsmqmx5ssYiRCU49NyZxjdGEjka5
🏁 round account = Dr4EWpnWT7fPiW3QqrJQsmqmx5ssYiRCU49NyZxjdGEjka5 / 9.8020 mKSM
🏁 round emoji = 🚀 / 1f680
🚀 Transaction broadcasted.
📀 Transaction remark(0x524d524b3a3a454d4f54453a3a312e302e303a3a363830323539352d3234643537336634646661316437666433332d4b414e2d4b414e4c2d303030303030303030303030333431343a3a3166363830) included at blockHash 0xb0ed9848c5e16d424e9ec7ab04cce1940f545d0e07a3104d0aec6c203058a464 [success = true]
💯 Transaction remark(..) Finalized at blockHash 0xb0ed9848c5e16d424e9ec7ab04cce1940f545d0e07a3104d0aec6c203058a464
🔜 next account is EkPjcd6xkgoBDj7hUE8yMRiiP1h4B4RS8qyFKqE6Shv5DGF [ivory pulse chaos cliff disorder believe napkin shoe okay mesh desert audit]
⏳ trying round 0: leftover = 9.7360 mKSM / fee = 17.6665 µKSM / epsilon = 4.8680 mKSM[4868001254, 2434000627] / trying to send 4.8503 mKSM2021-05-22 15:18:52        RPC-CORE: dryRun(extrinsic: Bytes, at?: BlockHash): ApplyExtrinsicResult:: -32601: Method not found
(node:35027) UnhandledPromiseRejectionWarning: Error: -32601: Method not found
    at RpcCoder._checkError (/root/kanaria-hatchery/kanaria-hatchery/node_modules/@polkadot/rpc-provider/coder/index.cjs:84:13)
    at RpcCoder.decodeResponse (/root/kanaria-hatchery/kanaria-hatchery/node_modules/@polkadot/rpc-provider/coder/index.cjs:47:10)
    at WsProvider.value (/root/kanaria-hatchery/kanaria-hatchery/node_modules/@polkadot/rpc-provider/ws/index.cjs:239:90)
    at W3CWebSocket.value [as onmessage] (/root/kanaria-hatchery/kanaria-hatchery/node_modules/@polkadot/rpc-provider/ws/index.cjs:219:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/root/kanaria-hatchery/kanaria-hatchery/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/root/kanaria-hatchery/kanaria-hatchery/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/root/kanaria-hatchery/kanaria-hatchery/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.EventEmitter.emit (domain.js:485:12)
    at WebSocketConnection.processFrame (/root/kanaria-hatchery/kanaria-hatchery/node_modules/websocket/lib/WebSocketConnection.js:554:26)
(Use node --trace-warnings ... to show where the warning was created)
(node:35027) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35027) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

In your example I don't see: `2021-05-22 15:18:34        API/INIT: RPC methods not decorated: state_getChildReadProof` like in my output
I'm running Kusama node v0.9.2 with the following flags: `--unsafe-rpc-external --unsafe-ws-external --rpc-cors all`
The starting address has 0.01 KSM

Thank you

**Comment by kianenigma** [comment]
Please paste the full command that you are using to run the node as well?

**Comment by Luca-Poggi** [comment]
`./polkadot --pruning 300 --chain=kusama --name "node_name" --base-path=/root/kusama-database --port 30333 --ws-port 9944 --rpc-port 9933 --prometheus-port 9615 --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --no-private-ipv4 --unsafe-rpc-external --unsafe-ws-external --rpc-cors all`

**Comment by kianenigma** [comment]
You are missing: `--rpc-methods Unsafe`.

I will reflect this in the README.

**Comment by Luca-Poggi** [comment]
Thank you!
