### ISSUE TITLE
Upstream issue?

### ISSUE THREAD

**Issue by x676f64** [kianenigma/kanaria-hatchery#5]
I don't know enough about npm to be intelligent on it but I am receiving this error. Could this be an upstream npm lib issue or am I just doing things wrong? I receive this error on two different machines. I am using a nmemonic phrase (./seed) for an account that has ~0.90 WNND in its wallet.

$ kanaria-hatchery --dust 100 --endpoint wss://westend-rpc.polkadot.io/ --final-account REDACTED --id DONT_CARE --seed ./seed --emotes 💸 😬 🐣 💻 📆 😈

2021-06-04 16:53:26        REGISTRY: Unable to resolve type MessageId, it will fail on construction
2021-06-04 16:53:26        API/INIT: RPC methods not decorated: state_getChildReadProof
2021-06-04 16:53:26        API/INIT: Error: FATAL: Unable to initialize the API: Unable to find closing matching <> on '(Vec<ProxyDefinition,BalanceOf)' (start 5)
    at EventEmitter.value (/usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/api/base/Init.cjs:91:25)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
2021-06-04 16:53:26        API/INIT: Error: Unable to find closing matching <> on '(Vec<ProxyDefinition,BalanceOf)' (start 5)
    at findClosing (/usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/types/create/sanitize.cjs:53:9)
    at /usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/types/create/sanitize.cjs:67:19
    at /usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/types/create/sanitize.cjs:180:42
    at Array.reduce (<anonymous>)
    at sanitize (/usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/types/create/sanitize.cjs:180:19)
    at getTypeDef (/usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/types/create/getTypeDef.cjs:170:39)
    at /usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/metadata/util/extractTypes.cjs:19:48
    at Array.map (<anonymous>)
    at extractTypes (/usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/metadata/util/extractTypes.cjs:18:16)
    at validateTypes (/usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/metadata/util/validateTypes.cjs:20:80)
2021-06-04 16:54:27          API-WS: disconnected from wss://westend-rpc.polkadot.io/: 1006:: Connection dropped by remote peer.
2021-06-04 16:54:32        API/INIT: RPC methods not decorated: state_getChildReadProof
2021-06-04 16:54:32        API/INIT: Error: FATAL: Unable to initialize the API: Unable to find closing matching <> on '(Vec<ProxyDefinition,BalanceOf)' (start 5)
    at EventEmitter.value (/usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/api/base/Init.cjs:91:25)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

**Comment by nichlor** [comment]
i have same issue... did they patch client so this scipt no longer works?

**Comment by martinloesethjensen** [comment]
@x676f64 and @x676f64 try and run `yarn add @polkadot/api` in the folder before running the script 😄  Let me know if it works

**Comment by x676f64** [comment]
Thanks for the reply Martin, that got me further but still dumping on the missing >

2021-06-10 14:49:32        REGISTRY: Unable to resolve type MessageId, it will fail on construction
2021-06-10 14:49:32        API/INIT: RPC methods not decorated: state_getChildReadProof
2021-06-10 14:49:32        API/INIT: Error: FATAL: Unable to initialize the API: Unable to find closing matching <> on '(Vec<ProxyDefinition,BalanceOf)' (start 5)
    at EventEmitter.value (/usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/api/base/Init.cjs:91:25)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
2021-06-10 14:49:32        API/INIT: Error: Unable to find closing matching <> on '(Vec<ProxyDefinition,BalanceOf)' (start 5)
    at findClosing (/usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/types/create/sanitize.cjs:53:9)
    at /usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/types/create/sanitize.cjs:67:19
    at /usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/types/create/sanitize.cjs:180:42
    at Array.reduce (<anonymous>)
    at sanitize (/usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/types/create/sanitize.cjs:180:19)
    at getTypeDef (/usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/types/create/getTypeDef.cjs:170:39)
    at /usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/metadata/util/extractTypes.cjs:19:48
    at Array.map (<anonymous>)
    at extractTypes (/usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/metadata/util/extractTypes.cjs:18:16)
    at validateTypes (/usr/local/lib/node_modules/kanaria-hatchery/node_modules/@polkadot/metadata/util/validateTypes.cjs:20:80)

**Comment by nichlor** [comment]
@martinloesethjensen what would it take for you to share your script O_o

**Comment by martinloesethjensen** [comment]
https://github.com/martinloesethjensen/rmrk-emote-batch 😈

**Comment by martinloesethjensen** [comment]
@x676f64 I think we can close this one 😄
